import { Inter } from "next/font/google";
import "./globals.css";
import TailwindThemeProvider from "./providers/tailwindThemeProvider";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    // adding suppressHydrationWarning as per next-themes official page
    // won't block hydration warnings on other elements
    // link: https://github.com/pacocoursey/next-themes#html--css

    <html lang="en" suppressHydrationWarning> 
      <body className={inter.className}>
        <TailwindThemeProvider>
          {children}
        </TailwindThemeProvider>
      </body>
    </html>
  );
}
