import { Inter } from "next/font/google";
import "./globals.css";
import TailwindThemeProvider from "./_providers/tailwindThemeProvider";
import DesktopNavbar from "./_components/desktopNav";
import SideBar from "./_components/sideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    // adding suppressHydrationWarning as per next-themes official page
    // won't block hydration warnings on other elements
    // link: https://github.com/pacocoursey/next-themes#html--css

    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <TailwindThemeProvider>
          <>
            <DesktopNavbar />
            <div className="flex sm:gap-10 justify-between w-screen max-w-full">
              <div className="relative sm:w-full sm:max-w-[18rem]">
                <input
                  type="checkbox"
                  id="sidebar-mobile-fixed"
                  className="sidebar-state"
                />
                <label
                  htmlFor="sidebar-mobile-fixed"
                  className="sidebar-overlay"
                ></label>
                <SideBar />
              </div>
              <div className="flex w-full flex-col p-4">
                <div className="w-fit">
                  <label htmlFor="sidebar-mobile-fixed" className="sm:hidden">
                    <svg
                      fill="currentColor"
                      className="h-6 w-6 opacity-75"
                      version="1.1"
                      id="Capa_1"
                      xmlns="http://www.w3.org/2000/svg"
                      width="24px"
                      height="24px"
                      viewBox="0 0 31.668 31.668"
                    >
                      <g>
                        <path
                          d="M31.501,0v5H12.167V0H31.501z M0.167,13.889h31.334v-5H0.167V13.889z M12.167,22.777h19.334v-5H12.167V22.777z
		 M0.167,31.668h31.334v-5H0.167V31.668z"
                        />
                      </g>
                    </svg>
                  </label>
                </div>
                {children}
              </div>
            </div>
          </>
        </TailwindThemeProvider>
      </body>
    </html>
  );
}
